// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_to_server_messages.proto

#include "client_to_server_messages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_client_5fto_5fserver_5fmessages_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_client_5fto_5fserver_5fmessages_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MoveRequest;
}  // namespace protobuf_client_5fto_5fserver_5fmessages_2eproto
namespace greyvarproto {
class ClientRequestsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientRequests>
      _instance;
} _ClientRequests_default_instance_;
class MoveRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MoveRequest>
      _instance;
} _MoveRequest_default_instance_;
class ConnectionRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectionRequest>
      _instance;
} _ConnectionRequest_default_instance_;
class NewPlayerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NewPlayer>
      _instance;
} _NewPlayer_default_instance_;
}  // namespace greyvarproto
namespace protobuf_client_5fto_5fserver_5fmessages_2eproto {
static void InitDefaultsClientRequests() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::greyvarproto::_ClientRequests_default_instance_;
    new (ptr) ::greyvarproto::ClientRequests();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::greyvarproto::ClientRequests::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ClientRequests =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsClientRequests}, {
      &protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_MoveRequest.base,}};

static void InitDefaultsMoveRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::greyvarproto::_MoveRequest_default_instance_;
    new (ptr) ::greyvarproto::MoveRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::greyvarproto::MoveRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MoveRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMoveRequest}, {}};

static void InitDefaultsConnectionRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::greyvarproto::_ConnectionRequest_default_instance_;
    new (ptr) ::greyvarproto::ConnectionRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::greyvarproto::ConnectionRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConnectionRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConnectionRequest}, {}};

static void InitDefaultsNewPlayer() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::greyvarproto::_NewPlayer_default_instance_;
    new (ptr) ::greyvarproto::NewPlayer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::greyvarproto::NewPlayer::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NewPlayer =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNewPlayer}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ClientRequests.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MoveRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectionRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NewPlayer.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::ClientRequests, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::ClientRequests, moverequest_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::MoveRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::MoveRequest, playerid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::MoveRequest, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::MoveRequest, y_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::ConnectionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::NewPlayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::greyvarproto::NewPlayer, username_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::greyvarproto::ClientRequests)},
  { 6, -1, sizeof(::greyvarproto::MoveRequest)},
  { 14, -1, sizeof(::greyvarproto::ConnectionRequest)},
  { 19, -1, sizeof(::greyvarproto::NewPlayer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::greyvarproto::_ClientRequests_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::greyvarproto::_MoveRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::greyvarproto::_ConnectionRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::greyvarproto::_NewPlayer_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "client_to_server_messages.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\037client_to_server_messages.proto\022\014greyv"
      "arproto\"@\n\016ClientRequests\022.\n\013moveRequest"
      "\030\001 \001(\0132\031.greyvarproto.MoveRequest\"5\n\013Mov"
      "eRequest\022\020\n\010playerId\030\001 \001(\005\022\t\n\001x\030\002 \001(\005\022\t\n"
      "\001y\030\003 \001(\005\"\023\n\021ConnectionRequest\"\035\n\tNewPlay"
      "er\022\020\n\010username\030\001 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 228);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "client_to_server_messages.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_client_5fto_5fserver_5fmessages_2eproto
namespace greyvarproto {

// ===================================================================

void ClientRequests::InitAsDefaultInstance() {
  ::greyvarproto::_ClientRequests_default_instance_._instance.get_mutable()->moverequest_ = const_cast< ::greyvarproto::MoveRequest*>(
      ::greyvarproto::MoveRequest::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientRequests::kMoveRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientRequests::ClientRequests()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_ClientRequests.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:greyvarproto.ClientRequests)
}
ClientRequests::ClientRequests(const ClientRequests& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_moverequest()) {
    moverequest_ = new ::greyvarproto::MoveRequest(*from.moverequest_);
  } else {
    moverequest_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:greyvarproto.ClientRequests)
}

void ClientRequests::SharedCtor() {
  moverequest_ = NULL;
}

ClientRequests::~ClientRequests() {
  // @@protoc_insertion_point(destructor:greyvarproto.ClientRequests)
  SharedDtor();
}

void ClientRequests::SharedDtor() {
  if (this != internal_default_instance()) delete moverequest_;
}

void ClientRequests::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ClientRequests::descriptor() {
  ::protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientRequests& ClientRequests::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_ClientRequests.base);
  return *internal_default_instance();
}


void ClientRequests::Clear() {
// @@protoc_insertion_point(message_clear_start:greyvarproto.ClientRequests)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && moverequest_ != NULL) {
    delete moverequest_;
  }
  moverequest_ = NULL;
  _internal_metadata_.Clear();
}

bool ClientRequests::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:greyvarproto.ClientRequests)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .greyvarproto.MoveRequest moveRequest = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_moverequest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:greyvarproto.ClientRequests)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:greyvarproto.ClientRequests)
  return false;
#undef DO_
}

void ClientRequests::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:greyvarproto.ClientRequests)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .greyvarproto.MoveRequest moveRequest = 1;
  if (this->has_moverequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_moverequest(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:greyvarproto.ClientRequests)
}

::google::protobuf::uint8* ClientRequests::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:greyvarproto.ClientRequests)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .greyvarproto.MoveRequest moveRequest = 1;
  if (this->has_moverequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_moverequest(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:greyvarproto.ClientRequests)
  return target;
}

size_t ClientRequests::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:greyvarproto.ClientRequests)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .greyvarproto.MoveRequest moveRequest = 1;
  if (this->has_moverequest()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *moverequest_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientRequests::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:greyvarproto.ClientRequests)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientRequests* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientRequests>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:greyvarproto.ClientRequests)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:greyvarproto.ClientRequests)
    MergeFrom(*source);
  }
}

void ClientRequests::MergeFrom(const ClientRequests& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:greyvarproto.ClientRequests)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_moverequest()) {
    mutable_moverequest()->::greyvarproto::MoveRequest::MergeFrom(from.moverequest());
  }
}

void ClientRequests::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:greyvarproto.ClientRequests)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientRequests::CopyFrom(const ClientRequests& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:greyvarproto.ClientRequests)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientRequests::IsInitialized() const {
  return true;
}

void ClientRequests::Swap(ClientRequests* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientRequests::InternalSwap(ClientRequests* other) {
  using std::swap;
  swap(moverequest_, other->moverequest_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClientRequests::GetMetadata() const {
  protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MoveRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MoveRequest::kPlayerIdFieldNumber;
const int MoveRequest::kXFieldNumber;
const int MoveRequest::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MoveRequest::MoveRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_MoveRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:greyvarproto.MoveRequest)
}
MoveRequest::MoveRequest(const MoveRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&playerid_, &from.playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&playerid_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:greyvarproto.MoveRequest)
}

void MoveRequest::SharedCtor() {
  ::memset(&playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&playerid_)) + sizeof(y_));
}

MoveRequest::~MoveRequest() {
  // @@protoc_insertion_point(destructor:greyvarproto.MoveRequest)
  SharedDtor();
}

void MoveRequest::SharedDtor() {
}

void MoveRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MoveRequest::descriptor() {
  ::protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MoveRequest& MoveRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_MoveRequest.base);
  return *internal_default_instance();
}


void MoveRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:greyvarproto.MoveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&playerid_)) + sizeof(y_));
  _internal_metadata_.Clear();
}

bool MoveRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:greyvarproto.MoveRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 playerId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 x = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 y = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:greyvarproto.MoveRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:greyvarproto.MoveRequest)
  return false;
#undef DO_
}

void MoveRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:greyvarproto.MoveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 playerId = 1;
  if (this->playerid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->playerid(), output);
  }

  // int32 x = 2;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->x(), output);
  }

  // int32 y = 3;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->y(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:greyvarproto.MoveRequest)
}

::google::protobuf::uint8* MoveRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:greyvarproto.MoveRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 playerId = 1;
  if (this->playerid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->playerid(), target);
  }

  // int32 x = 2;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->x(), target);
  }

  // int32 y = 3;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->y(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:greyvarproto.MoveRequest)
  return target;
}

size_t MoveRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:greyvarproto.MoveRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 playerId = 1;
  if (this->playerid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerid());
  }

  // int32 x = 2;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  // int32 y = 3;
  if (this->y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MoveRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:greyvarproto.MoveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const MoveRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MoveRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:greyvarproto.MoveRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:greyvarproto.MoveRequest)
    MergeFrom(*source);
  }
}

void MoveRequest::MergeFrom(const MoveRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:greyvarproto.MoveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.playerid() != 0) {
    set_playerid(from.playerid());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void MoveRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:greyvarproto.MoveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MoveRequest::CopyFrom(const MoveRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:greyvarproto.MoveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MoveRequest::IsInitialized() const {
  return true;
}

void MoveRequest::Swap(MoveRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MoveRequest::InternalSwap(MoveRequest* other) {
  using std::swap;
  swap(playerid_, other->playerid_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MoveRequest::GetMetadata() const {
  protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ConnectionRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionRequest::ConnectionRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_ConnectionRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:greyvarproto.ConnectionRequest)
}
ConnectionRequest::ConnectionRequest(const ConnectionRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:greyvarproto.ConnectionRequest)
}

void ConnectionRequest::SharedCtor() {
}

ConnectionRequest::~ConnectionRequest() {
  // @@protoc_insertion_point(destructor:greyvarproto.ConnectionRequest)
  SharedDtor();
}

void ConnectionRequest::SharedDtor() {
}

void ConnectionRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectionRequest::descriptor() {
  ::protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionRequest& ConnectionRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_ConnectionRequest.base);
  return *internal_default_instance();
}


void ConnectionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:greyvarproto.ConnectionRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ConnectionRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:greyvarproto.ConnectionRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:greyvarproto.ConnectionRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:greyvarproto.ConnectionRequest)
  return false;
#undef DO_
}

void ConnectionRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:greyvarproto.ConnectionRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:greyvarproto.ConnectionRequest)
}

::google::protobuf::uint8* ConnectionRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:greyvarproto.ConnectionRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:greyvarproto.ConnectionRequest)
  return target;
}

size_t ConnectionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:greyvarproto.ConnectionRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:greyvarproto.ConnectionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:greyvarproto.ConnectionRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:greyvarproto.ConnectionRequest)
    MergeFrom(*source);
  }
}

void ConnectionRequest::MergeFrom(const ConnectionRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:greyvarproto.ConnectionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ConnectionRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:greyvarproto.ConnectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionRequest::CopyFrom(const ConnectionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:greyvarproto.ConnectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionRequest::IsInitialized() const {
  return true;
}

void ConnectionRequest::Swap(ConnectionRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionRequest::InternalSwap(ConnectionRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectionRequest::GetMetadata() const {
  protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NewPlayer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NewPlayer::kUsernameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NewPlayer::NewPlayer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_NewPlayer.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:greyvarproto.NewPlayer)
}
NewPlayer::NewPlayer(const NewPlayer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  // @@protoc_insertion_point(copy_constructor:greyvarproto.NewPlayer)
}

void NewPlayer::SharedCtor() {
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

NewPlayer::~NewPlayer() {
  // @@protoc_insertion_point(destructor:greyvarproto.NewPlayer)
  SharedDtor();
}

void NewPlayer::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NewPlayer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NewPlayer::descriptor() {
  ::protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NewPlayer& NewPlayer::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_client_5fto_5fserver_5fmessages_2eproto::scc_info_NewPlayer.base);
  return *internal_default_instance();
}


void NewPlayer::Clear() {
// @@protoc_insertion_point(message_clear_start:greyvarproto.NewPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool NewPlayer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:greyvarproto.NewPlayer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string username = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "greyvarproto.NewPlayer.username"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:greyvarproto.NewPlayer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:greyvarproto.NewPlayer)
  return false;
#undef DO_
}

void NewPlayer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:greyvarproto.NewPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string username = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "greyvarproto.NewPlayer.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:greyvarproto.NewPlayer)
}

::google::protobuf::uint8* NewPlayer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:greyvarproto.NewPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string username = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "greyvarproto.NewPlayer.username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:greyvarproto.NewPlayer)
  return target;
}

size_t NewPlayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:greyvarproto.NewPlayer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string username = 1;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NewPlayer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:greyvarproto.NewPlayer)
  GOOGLE_DCHECK_NE(&from, this);
  const NewPlayer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NewPlayer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:greyvarproto.NewPlayer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:greyvarproto.NewPlayer)
    MergeFrom(*source);
  }
}

void NewPlayer::MergeFrom(const NewPlayer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:greyvarproto.NewPlayer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
}

void NewPlayer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:greyvarproto.NewPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewPlayer::CopyFrom(const NewPlayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:greyvarproto.NewPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewPlayer::IsInitialized() const {
  return true;
}

void NewPlayer::Swap(NewPlayer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NewPlayer::InternalSwap(NewPlayer* other) {
  using std::swap;
  username_.Swap(&other->username_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NewPlayer::GetMetadata() const {
  protobuf_client_5fto_5fserver_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_client_5fto_5fserver_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace greyvarproto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::greyvarproto::ClientRequests* Arena::CreateMaybeMessage< ::greyvarproto::ClientRequests >(Arena* arena) {
  return Arena::CreateInternal< ::greyvarproto::ClientRequests >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::greyvarproto::MoveRequest* Arena::CreateMaybeMessage< ::greyvarproto::MoveRequest >(Arena* arena) {
  return Arena::CreateInternal< ::greyvarproto::MoveRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::greyvarproto::ConnectionRequest* Arena::CreateMaybeMessage< ::greyvarproto::ConnectionRequest >(Arena* arena) {
  return Arena::CreateInternal< ::greyvarproto::ConnectionRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::greyvarproto::NewPlayer* Arena::CreateMaybeMessage< ::greyvarproto::NewPlayer >(Arena* arena) {
  return Arena::CreateInternal< ::greyvarproto::NewPlayer >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
