// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_interface.proto

#include "server_interface.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace greyvarproto {
}  // namespace greyvarproto
namespace protobuf_server_5finterface_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "server_interface.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026server_interface.proto\022\014greyvarproto\032\037"
      "client_to_server_messages.proto\032\037server_"
      "to_client_messages.proto2\372\001\n\017ServerInter"
      "face\022N\n\007Connect\022\037.greyvarproto.Connectio"
      "nRequest\032 .greyvarproto.ConnectionRespon"
      "se\"\000\022B\n\013PlayerSetup\022\027.greyvarproto.NewPl"
      "ayer\032\030.greyvarproto.NoResponse\"\000\022S\n\016GetS"
      "erverFrame\022\034.greyvarproto.ClientRequests"
      "\032!.greyvarproto.ServerFrameResponse\"\000b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 365);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "server_interface.proto", &protobuf_RegisterTypes);
  ::protobuf_client_5fto_5fserver_5fmessages_2eproto::AddDescriptors();
  ::protobuf_server_5fto_5fclient_5fmessages_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_server_5finterface_2eproto
namespace greyvarproto {

// @@protoc_insertion_point(namespace_scope)
}  // namespace greyvarproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
